import type { Playbook } from "./playbooks";
import { withTrackOrder } from "./playbooks";

const FOUNDER_PLAYBOOKS_DATA: Omit<Playbook, "order">[] = [
  {
    id: "ai-fundamentals-for-founders",
    title: "AI Fundamentals for Founders",
    subtitle: "Technical fluency for founders who lead strategy, not write code.",
    description:
      "The AI hierarchy, cost lines, data advantage, evaluation, liability, and market structure — explained for founders making strategy and funding decisions.",
    difficulty: "Intermediate",
    readingMinutes: 28,
    topics: [
      "AI vs ML vs DL (founder lens)",
      "How models learn & what it costs",
      "Training vs inference cost lines",
      "Data as competitive advantage",
      "Probability & confidence for founders",
      "Model evaluation for non-technical founders",
      "Bias, hallucination & founder liability",
      "AI landscape & market structure",
    ],
    sequence: [],
  },
  {
    id: "building-ai-native-company",
    title: "Building an AI-Native Company",
    subtitle: "Architect a company where AI is the product, not a bolt-on feature.",
    description:
      "From AI-native vs AI-washed positioning to data moats, flywheels, and infrastructure stack choices that compound over time.",
    difficulty: "Intermediate",
    readingMinutes: 35,
    topics: [
      "AI-native vs AI-powered vs AI-washed",
      "Data architecture decisions",
      "Feedback loop business model",
      "Building your data moat",
      "Proprietary data strategy",
      "AI-native product architecture",
      "Model-agnostic vs model-committed",
      "Synthetic data",
      "Data flywheel design",
      "AI infrastructure stack decisions",
    ],
    sequence: [],
  },
  {
    id: "ai-strategy-competitive-positioning",
    title: "AI Strategy & Competitive Positioning",
    subtitle: "Find your wedge and defend it in AI markets.",
    description:
      "Competitive positioning for AI businesses — defensibility, moats, vertical vs horizontal bets, and escaping the wrapper trap.",
    difficulty: "Advanced",
    readingMinutes: 35,
    topics: [
      "Porter's Five Forces for AI markets",
      "Finding your AI wedge",
      "Where AI creates defensibility",
      "Data moats vs distribution moats",
      "Switching costs in AI products",
      "The wrapper problem & how to escape it",
      "Vertical AI vs horizontal AI",
      "Stress-testing your strategy",
      "AI feature vs AI business distinction",
      "Competitive response planning",
    ],
    sequence: [],
  },
  {
    id: "funding-valuation-ai-premium",
    title: "Funding, Valuation & the AI Premium",
    subtitle: "Navigate the AI valuation premium and investor expectations.",
    description:
      "How VCs evaluate AI companies, what justifies multiples, due diligence prep, and fundraising narratives from seed to growth.",
    difficulty: "Intermediate",
    readingMinutes: 35,
    topics: [
      "How VCs evaluate AI companies",
      "The AI valuation premium",
      "What justifies an AI multiple",
      "Due diligence questions investors will ask",
      "AI metrics investors actually care about",
      "Telling your AI story without overpromising",
      "Seed vs Series A vs growth stage AI narratives",
      "Cap table implications",
      "AI-native financial model",
      "Fundraising red flags to avoid",
    ],
    sequence: [],
  },
  {
    id: "ai-team-building-org-design",
    title: "AI Team Building & Org Design",
    subtitle: "Hire, structure, and retain AI talent before you feel ready.",
    description:
      "Org design for AI-native startups — role clarity, first hires, compensation, culture, and interviewing without a technical co-founder.",
    difficulty: "Intermediate",
    readingMinutes: 35,
    topics: [
      "ML Engineer vs AI Engineer vs Data Scientist",
      "When to hire your first AI lead",
      "Founding team AI literacy",
      "AI org chart design",
      "Compensation benchmarks for AI talent",
      "Contractors vs consultants vs full-time",
      "Building AI culture without AI washing",
      "Interviewing AI candidates as a non-technical founder",
      "Team structure at seed vs Series A vs Series B",
      "AI talent retention",
    ],
    sequence: [],
  },
  {
    id: "ai-vendor-build-buy-decisions",
    title: "AI Vendor, Build & Buy Decisions",
    subtitle: "Build vs buy vs API — with eyes open on total cost.",
    description:
      "Vendor evaluation, lock-in risk, model provider decisions, and contract negotiation for founders making irreversible infrastructure bets.",
    difficulty: "Intermediate",
    readingMinutes: 35,
    topics: [
      "Total cost of ownership — build vs buy",
      "API dependency risk",
      "Vendor lock-in & exit strategy",
      "Evaluating AI infrastructure vendors",
      "OpenAI vs Anthropic vs open source decision",
      "When to build your own model",
      "Fine-tuning vs RAG vs prompt engineering cost comparison",
      "Vendor due diligence checklist",
      "Contract negotiation with AI vendors",
      "Multi-vendor strategy",
    ],
    sequence: [],
  },
  {
    id: "ai-risk-governance-founders",
    title: "AI Risk, Safety & Governance for Founders",
    subtitle: "Compliance, liability, and governance without a legal department.",
    description:
      "EU AI Act, US regulation, board-level governance, red-teaming, and turning responsible AI into a commercial advantage.",
    difficulty: "Advanced",
    readingMinutes: 38,
    topics: [
      "EU AI Act — what founders must know now",
      "US regulatory landscape 2025",
      "High-risk AI categories & compliance",
      "Legal liability for AI outputs",
      "Hallucination liability by vertical",
      "Bias as legal and reputational risk",
      "Board-level AI governance",
      "Minimum viable AI compliance stack",
      "Red-teaming your own product",
      "AI incident response playbook",
      "Responsible AI as a commercial advantage",
    ],
    sequence: [],
  },
  {
    id: "scaling-ai-product",
    title: "Scaling an AI Product",
    subtitle: "Unit economics and org design when AI products hit traction.",
    description:
      "Cost curves, degradation at scale, vendor switching, and building for 10× growth without 10× burn.",
    difficulty: "Advanced",
    readingMinutes: 35,
    topics: [
      "Infrastructure cost curves at scale",
      "Unit economics inflection points",
      "Model performance degradation at scale",
      "Data quality problems that appear only at scale",
      "When to switch models or vendors",
      "Organisational scaling alongside technical scaling",
      "AI product at Series A vs Series B",
      "Latency at scale",
      "Cost optimisation at scale",
      "Building for 10x growth without 10x costs",
    ],
    sequence: [],
  },
];

export const FOUNDER_PLAYBOOKS: Playbook[] = withTrackOrder(FOUNDER_PLAYBOOKS_DATA);
